# Generated by Django 6.0.2 on 2026-02-24 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_entrance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoo_name', models.CharField(max_length=25, unique=True)),
                ('zoo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_entrance.zoouser')),
            ],
        ),
        migrations.CreateModel(
            name='ZooAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25, unique=True)),
                ('species', models.CharField(max_length=25)),
                ('food', models.CharField(max_length=50)),
                ('zoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_entrance.zoo')),
            ],
        ),
    ]
