# Generated by Django 6.0.2 on 2026-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_entrance', '0002_zoo_zooanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoo',
            name='zoo_location',
            field=models.CharField(default='Indianapolis', max_length=25),
        ),
    ]
